### ISSUE TITLE
Fix Action Organization ("release-tektoncd-task")

### ISSUE THREAD

**Issue by otaviof** [openshift-pipelines/task-containers#43]
https://github.com/openshift-pipelines/task-containers/blob/75564f7794c2d25870d7e5471e7f45dbda806bc7/.github/workflows/release.yaml#L17-L19

This action should be coming from [`openshift-pipelines/release-tektoncd-task`](https://github.com/openshift-pipelines/release-tektoncd-task)

**Comment by otaviof** [comment]
As a reference, when releasing without a tag created (matching the chart version) the release script fails at:

https://github.com/openshift-pipelines/release-tektoncd-task/blob/f592bf90e74ab5d5daea30fb464f5cf63b3928e2/inputs.sh#L54-L56

Let's also improve our documentation to show the steps needed to release.

**Comment by Senjuti256** [comment]
Issue resolved through PR 45.
